### ISSUE TITLE
Not a real web3 wallet

### ISSUE THREAD

**Issue by crosschainer** [3Dpass/wallet#4]
Example Substrate Wallet:
https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd

If smart contracts are a thing, we need injection of accounts into dapps(websites) and be able to sign transactions using the wallet.

**Comment by PaulSff** [comment]
From my understanding, what you're talking about is as the browser extension or external keys storage. We have a plan to add  it, however, the actual wallet allows to sign transactions with the addresses imported.  So, it's an absolutely real one.
